appointments/urls.py
from django.urls import path, include
from . import views
from .views import schedule_appointment

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('', views.base_page, name='base'),
    path('base/', views.base_page, name='base'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('scheduler/', views.appointment_scheduler, name='appointment_scheduler'),
    path('schedule_appointment/', schedule_appointment, name='schedule_appointment'),
    path('query_list/', schedule_appointment, name='query_list'),
    path('history/', views.appointment_history, name='appointment_history'),
    # Adicione outras URLs conforme necessário
]

healthcare_project/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointments.urls')),
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User


class HealthProfessional(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Appointment(models.Model):
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    health_professional = models.ForeignKey(HealthProfessional, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Appointment {self.pk} - {self.health_professional} - {self.date} {self.time}"

appointments/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from appointments.models import Appointment, HealthProfessional


class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class AppointmentForm(forms.ModelForm):
    appointment_date = forms.DateField(widget=forms.DateInput(attrs={'id': 'datepicker'}))

    class Meta:
        model = Appointment
        fields = ['health_professional', 'appointment_date']  # Corrija o nome do campo para 'health_professional'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            'health_professional'].queryset = HealthProfessional.objects.all()  # Ajuste para 'health_professional'

appointments/views.py
from datetime import datetime

import requests
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse, HttpResponseServerError
from django.shortcuts import render, redirect

from .forms import SignUpForm, AppointmentForm
from .models import Appointment, HealthProfessional


def appointment_history(request):
    try:
        # Obtenha todas as consultas do banco de dados
        appointments = Appointment.objects.all()

        # Renderize o template com os dados das consultas no contexto
        return render(request, 'appointment_history.html', {'appointments': appointments})
    except Exception as e:
        # Se ocorrer um erro, imprima o erro no console para fins de depuração
        print(f"Erro ao renderizar a página de histórico de consultas: {e}")
        # Retorne uma resposta HTTP com um status de erro 500 (Internal Server Error)
        return HttpResponseServerError("Ocorreu um erro ao processar sua solicitação. Por favor, tente novamente mais tarde.")


def appointment_scheduler(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.user = request.user
            appointment.save()
            return redirect('appointment_history')
    else:
        form = AppointmentForm()
    return render(request, 'appointment_scheduler.html', {'form': form})


def get_available_times(request):
    selected_date = request.GET.get('appointment_date')
    health_professional_id = request.GET.get('health_professional')
    available_times = fetch_available_times_from_legacy_system(selected_date, health_professional_id)
    return JsonResponse(available_times, safe=False)


def fetch_available_times_from_legacy_system(selected_date, health_professional_id):
    try:
        response = requests.get(
            f'https://sistema-legado.com/api/appointments/{selected_date}/{health_professional_id}/times')
        if response.status_code == 200:
            return response.json()
        else:
            return []
    except requests.RequestException as e:
        print(
            f"Erro ao obter horários disponíveis para a data {selected_date} e profissional {health_professional_id}: {e}")
        return ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00']


def schedule_appointment(request):
    if request.method == 'POST':
        user = request.user
        health_professional_id = request.POST.get('health_professional')
        date = request.POST.get('appointment_date')
        time = request.POST.get('time')

        health_professional = HealthProfessional.objects.get(id=health_professional_id)

        # Criar o objeto de consulta agendada
        Appointment.objects.create(user=user, health_professional=health_professional, date=date,
                                   time=time)

        # Redirecionar para a página de histórico de consultas
        appointments = Appointment.objects.filter(user=user)
        return render(request, 'appointment_history.html', {'appointments': appointments})

    # Se não for uma solicitação POST, renderizar a página de agendamento com os horários disponíveis
    professionals = HealthProfessional.objects.all()
    selected_date = request.GET.get('appointment_date')
    available_times = get_available_times(selected_date)
    return render(request, 'appointment_schedule.html',
                  {'professionals': professionals, 'available_times': available_times})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(
                    'user_profile')  # Redireciona para a página do perfil do usuário após o login bem-sucedido
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('base')  # Redireciona para a página inicial após o cadastro bem-sucedido
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def logout_view():
    # Your logout logic here
    return redirect('base')


def user_profile(request):
    # Lógica para renderizar a página do perfil do usuário
    return render(request, 'user_profile.html')


def base_page(request):
    return render(request, 'base.html')

templates/appointment_history.html
{% extends 'base.html' %}

{% block title %}Histórico de Consultas{% endblock %}

{% block content %}
<div class="container">
    <h1>Lista de Consultas</h1>
    <ul>
        {% for appointment in appointments %}
        <li>{{ appointment.health_professional }} - {{ appointment.date }} às {{ appointment.time }}</li>
        {% empty %}
        <li>Nenhuma consulta agendada.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/appointment_scheduler.html
{% extends 'base.html' %}

{% block title %}Agendamento de Consultas{% endblock %}

{% block content %}
<div class="container">
    <h1>Agendamento de Consultas</h1>
    <form method="post" action="{% url 'schedule_appointment' %}">
        {% csrf_token %}
        <label for="id_health_professional">Profissional de Saúde:</label>
        <select name="health_professional" id="id_health_professional">
            {% for professional in professionals %}
                <option value="{{ professional.id }}">{{ professional.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="id_appointment_date">Data da Consulta:</label>
        <input type="text" id="id_appointment_date">
        <br>
        <label>Horários Disponíveis:</label>
        <div id="available-times">
            <!-- Aqui serão exibidos os horários disponíveis dinamicamente -->
        </div>
        <br>
        <button type="submit">Agendar</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script>
    $(document).ready(function() {
        // Função para abrir o Datepicker quando o campo "Data da Consulta" for clicado
        $('#id_appointment_date').datepicker();

        // Função para carregar os horários disponíveis ao selecionar uma data e profissional
        $('#id_appointment_date, #id_health_professional').change(function() {
            var selectedDate = $('#id_appointment_date').val();
            var selectedProfessional = $('#id_health_professional').val();
            $.ajax({
                type: 'GET',
                url: '/get_available_times/',
                data: {
                    'appointment_date': selectedDate,
                    'health_professional': selectedProfessional
                },
                success: function(data) {
                    $('#available-times').empty();
                    $.each(data, function(index, value) {
                        $('#available-times').append('<label><input type="radio" name="time" value="' + value + '">' + value + '</label><br>');
                    });
                }
            });
        });
    });
</script>
{% endblock %}

templates/base.html
<!-- base.html -->
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    <div id="content">
        {% block content %}
        <div class="container">
            <h1>Bem-vindo à Página Inicial</h1>
            <p>Aqui você pode fazer login ou se cadastrar.</p>
            <a href="{% url 'login' %}">Fazer Login</a>
            <a href="{% url 'signup' %}">Cadastrar-se</a>
        </div>
        {% endblock %}
    </div>
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Cadastro{% endblock %}

{% block content %}
<div class="container">
    <h1>Cadastro</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Cadastrar</button>
    </form>
</div>
{% endblock %}

templates/user_profile.html
<!-- user_profile.html -->

{% extends 'base.html' %}

{% block title %}Perfil do Usuário{% endblock %}

{% block content %}
<div class="container">
    <h1>Perfil do Usuário</h1>
    <p>Informações do usuário:</p>
    <ul>
        <li>Nome: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
        <!-- Adicione outras informações do usuário conforme necessário -->
    </ul>
    <a href="{% url 'appointment_scheduler' %}" class="btn btn-primary">Agendar Consulta</a>
</div>
{% endblock %}